language: ruby

rvm:
  - 2.1
  - ruby-head
  - rbx-2

os:
  - linux

gemfile:
  - Gemfile
  - Gemfile.cool.io.1.1.1

script: bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
